# -*- coding: utf-8 -*-
"""Face_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbeGeLpqKe7526HkRufjHxCf3fY1nlqf
"""

# Unpickling the data
import pickle

with open('/content/Images.p', 'rb') as f:
    Images = pickle.load(f)
with open('/content/labels.p', 'rb') as f:
    labels = pickle.load(f)

print(Images.shape)
print(labels.shape)

(199,100,100)
(199,)

labels

set(labels)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

labels = le.fit_transform(labels)
set(labels)

le.inverse_transform([0,1])

print(le.classes_)

p = len(set(labels))
print("Toatal number of persons: ",p)

import matplotlib.pyplot as plt
plt.imshow(Images[155],cmap='gray')
plt.show()

import cv2

from numpy import reshape
def preprocessing(img):
  img = cv2.equalizeHist(img)
  img = img.reshape(100,100,1)
  img = img/255
  return img

import numpy as np

images = np.array(list(map(preprocessing,Images)))
print("Shape of Input Data:",images.shape)

from keras.utils import to_categorical
labels = to_categorical(labels)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(images,labels,test_size=0.2)

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from keras.layers import Conv2D,MaxPooling2D,Flatten

model = Sequential()
#convolutional and Relu Layer
model.add(Conv2D(32,(3,3),input_shape=(100,100,1),activation='relu'))
# Pooling layer
model.add(MaxPooling2D(pool_size=(2,2)))

#Convolutional layer and ReLU layer
model.add(Conv2D(64,(3,3),activation="relu"))
#Pooling Layer
model.add(MaxPooling2D(pool_size=(2,2)))

#Flatten Layer/Input Layer
model.add(Flatten())

#Hidden Layer
model.add(Dense(200,activation='relu'))
model.add(Dense(100,activation = 'relu'))

#Output Layer
model.add(Dense(p,activation='softmax'))
model.compile(Adam(learning_rate=0.01),loss='categorical_crossentropy',metrics=['accuracy'])

model.summary()

model.fit(x_train,y_train,epochs=20,batch_size=32,validation_data=(x_test, y_test),verbose=1)

model.save("Final_Model.h5")







